server:
  port: 8082
spring:
  kafka:
    consumer:

      "bootstrap.servers": localhost:9092
      "enable.auto.commit": true
      "max.poll.records": 500
      "max.poll.interval.ms": 180000
      "max.partition.fetch.bytes": 2147483647
      "session.timeout.ms": 60000
      "heartbeat.interval.ms": 500
      "fetch.max.bytes": 2147483647
      "auto.offset.reset": earliest
      "spring.json.value.default.type": json
      "spring.json.trusted.packages": "*"
      group-id: "default"
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      auto-offset-reset: earliest
    containerFactory:
      concurrency: 1
      decrypt-messages: false
      encrypt-messages: false
      ack-mode: RECORD
      batch-listener: false
      missing-topic-fatal: false
  data:
    mongodb:
      database: mydb
      port: 27017
      host: localhost


